apiVersion: apps/v1
kind: Deployment
metadata:
  name: petrosa-tradeengine
  namespace: petrosa-apps
  labels:
    app: petrosa-tradeengine
    version: VERSION_PLACEHOLDER
spec:
  replicas: 3
  selector:
    matchLabels:
      app: petrosa-tradeengine
  template:
    metadata:
      labels:
        app: petrosa-tradeengine
        version: VERSION_PLACEHOLDER
    spec:
      containers:
      - name: petrosa-tradeengine
        image: yurisa2/petrosa-tradeengine:VERSION_PLACEHOLDER
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        # Environment configuration from existing configmap
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: petrosa-common-config
              key: environment
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: petrosa-common-config
              key: log-level
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"
        # MongoDB configuration from secret
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: petrosa-sensitive-credentials
              key: mongodb-connection-string
        - name: MONGODB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: petrosa-common-config
              key: MONGODB_DATABASE
        # NATS configuration from configmap
        - name: NATS_ENABLED
          valueFrom:
            configMapKeyRef:
              name: petrosa-common-config
              key: NATS_ENABLED
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: petrosa-common-config
              key: NATS_URL
        # Trading configuration from existing configmap
        - name: SIMULATION_ENABLED
          valueFrom:
            configMapKeyRef:
              name: petrosa-common-config
              key: simulation-enabled
        - name: BINANCE_TESTNET
          valueFrom:
            configMapKeyRef:
              name: petrosa-common-config
              key: binance-testnet
        - name: RISK_MANAGEMENT_ENABLED
          value: "true"
        # Risk management limits
        - name: MAX_POSITION_SIZE_PCT
          value: "0.1"
        - name: MAX_DAILY_LOSS_PCT
          value: "0.05"
        - name: MAX_PORTFOLIO_EXPOSURE_PCT
          value: "0.8"
        # Distributed lock configuration
        - name: LOCK_TIMEOUT_SECONDS
          value: "60"
        - name: HEARTBEAT_INTERVAL_SECONDS
          value: "10"
        # Monitoring configuration
        - name: PROMETHEUS_ENABLED
          value: "true"
        - name: HEALTH_CHECK_INTERVAL
          value: "30"
        # JWT configuration
        - name: JWT_ALGORITHM
          value: "HS256"
        - name: JWT_EXPIRATION_HOURS
          value: "24"
        # Secrets from existing secret
        - name: BINANCE_API_KEY
          valueFrom:
            secretKeyRef:
              name: petrosa-sensitive-credentials
              key: BINANCE_API_KEY
        - name: BINANCE_API_SECRET
          valueFrom:
            secretKeyRef:
              name: petrosa-sensitive-credentials
              key: BINANCE_API_SECRET
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: petrosa-sensitive-credentials
              key: JWT_SECRET_KEY
        # Pod information for distributed state
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /live
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      restartPolicy: Always
      terminationGracePeriodSeconds: 30 