name: CI Checks

on:
  workflow_dispatch:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  release:
    types: [published]

jobs:
  pipeline:
    name: CI Pipeline
    uses: PetroSa2/petrosa-shared-workflows/.github/workflows/ci-pipeline.yml@main
    with:
      service-name: 'tradeengine'
      image-name: 'yurisa2/petrosa-tradeengine'
      python-version: '3.11'
      skip-docker-build: true
    secrets: inherit
