name: Debug Secret

on:
  workflow_dispatch:

jobs:
  debug-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Debug KUBE_CONFIG_DATA
      run: |
        echo "=== KUBE_CONFIG_DATA Secret (Base64 Encoded) ==="
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -w 0
        echo ""
        echo "=== Decoded KUBE_CONFIG_DATA ==="
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode
        echo ""
        echo "=== Secret Length ==="
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | wc -c
